#!/usr/bin/perl
use strict;
use warnings;
use 5.010;
use autodie qw/ open close /;

use XML::LibXML;
use Data::Dumper;

my ($file, $url, $sha) = @ARGV;

my $dom = XML::LibXML->load_xml(location => $file);
my $root = $dom->documentElement();
my ($scm) = $root->findnodes(q{/services/service[@name='obs_scm']});

my ($urlnode) = $scm->findnodes(q{param[@name='url']});
unless ($urlnode) {
    die "Could not find url parameter";
}
$urlnode->removeChildNodes;
$urlnode->appendText($url);
my ($shanode) = $scm->findnodes(q{param[@name='revision']});
unless ($shanode) {
    die "Could not find revision parameter";
}
$shanode->removeChildNodes;
$shanode->appendText($sha);

open my $fh, '>', $file;
print $fh $dom;
close $fh;
