on:
- push
#- pull_request

jobs:
  obs:
    runs-on: ubuntu-latest
    name: OBS
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - run: env | sort

    - name: Branch OBS Project
      uses: ./ # Uses an action in the root directory
      id: obs
      with:
        apiurl: https://api.opensuse.org
        project: devel:openQA
        package: os-autoinst
        branchprefix: home:$USER:branches:TestGitHub
        ignore-repos: SLE_12_SP5,SLE_12_SP4,SLE_12_SP3,openSUSE_Leap_15.0
      env:
        OSCLOGIN: ${{ secrets.OSCLOGIN }}
        OSCPASS: ${{ secrets.OSCPASS }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Path to branched package
      run: echo "${{ steps.obs.outputs.branch }}"
